# Generated by Django 4.0.5 on 2022-06-10 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'Админ'), ('2', 'Mенеджер'), ('3', 'Оператор')], default='1', max_length=255, verbose_name='Тип пользователя'),
        ),
    ]
